[remote_datbase_secrets]
host = "dpg-cok20ngcmk4c73c6qjo0-a.oregon-postgres.render.com"
port = 5432
db_name='filtersdb_xmcb'
username = "filtersdb_user"
password = "54VHUQGRf77cadzLAss91HU2A9jQe3xU"
filter_table='filters'
database_table='sitesdatabase'
type='postgresql'
