[datbase_secrets]
host = "localhost"
port = 3306
db_name='filtersdb'
username = "root"
password = ""
filter_table='filters'
database_table='sitesdatabase'
type='mysql+pymysql'

[remote_datbase_secrets]
host = "dpg-cmgr5ata73kc73dsi8i0-a.frankfurt-postgres.render.com"
port = 5432
db_name='filtersdb'
username = "filtersdb_user"
password = "riamjBpNN96d28jsEZ43u4sqGJwQD4zb"
filter_table='filters'
database_table='sitesdatabase'
type='postgresql'


[remote_datbase_secrets_new]
host = "mysql-21ab9b73-mohamed-3916.a.aivencloud.com"
port = 26494
db_name='defaultdb'
username = "avnadmin"
password = "AVNS_2ier57-eiRsQ9douQlV"
filter_table='filters'
database_table='sitesdatabase'
type='mysql+pymysql'